brew "colima"
brew "docker"
brew "docker-compose"
brew "go"
brew "hugo"
brew "mas"
brew "mole"
brew "nvm"
brew "tmux"

cask "focusrite-control-2"
cask "quicken"
cask "signal"
cask "visual-studio-code"

mas "Ivory", id: 6444602274
mas "Keynote", id: 361285480
mas "Numbers", id: 361304891
mas "Pages", id: 361309726
mas "Pixelmator Pro", id: 6746662575
mas "Tailscale", id: 1475387142
mas "Unread", id: 1363637349
mas "Wipr", id: 1662217862