tap "chriswiegman/backup-github", trusted: true

brew "hugo"
brew "mas"
brew "mise"
brew "mole"
brew "tmux"

cask "chriswiegman/backup-github/backup-github"
cask "focusrite-control-2"
cask "protonvpn"
cask "signal"
cask "visual-studio-code"

mas "Banktivity", id: 1480779512
mas "Keynote", id: 361285480
mas "Numbers", id: 361304891
mas "Pages", id: 361309726
mas "Pixelmator Pro", id: 6746662575
mas "Unread", id: 1363637349
mas "Wipr", id: 1662217862
mas "Xcode", id: 497799835
