brew "gh"
brew "mas"
brew "mise"
brew "mole"
brew "tmux"

cask "font-sf-mono"
cask "visual-studio-code"

mas "1Password for Safari", id: 1569813296
mas "Okta Verify", id: 490179405
mas "Wipr", id: 1662217862