tap "homebrew/cask-fonts"

brew "nvm"
brew "tmux"

cask "aldente"
cask "bartender"
cask "discord"
cask "elgato-control-center"
cask "focusrite-control"
cask "font-jetbrains-mono"
cask "local"
cask "logitech-camera-settings"
cask "visual-studio-code"
